apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app
spec:
  replicas: 3  # Number of replicas/instances of the application
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress-app-container
        image: yashu12/wordpress  # Replace with your Docker image
        ports:
        - containerPort: 80  # Replace with the port your Python app listens on



apiVersion: v1
kind: Service
metadata:
  name: wordpress-app-service
spec:
  selector:
    app: wordpress-app
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will be exposed
      targetPort: 80  # Port on which your Python app is running in the container
  type: LoadBalancer  # Expose the service outside the Kubernetes clust
